import { useMemo, useState } from 'react';
import { WalletCards, TrendingUp, TrendingDown, PiggyBank, Target, Sparkles, Plus, Trash2, Send, Lightbulb, BarChart3 } from 'lucide-react';

type Tx={id:number;description:string;amount:number;type:'income'|'expense';category:string};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const initial:Tx[]=[
{id:1,description:'Salário',amount:3200,type:'income',category:'Renda'},
{id:2,description:'Aluguel',amount:900,type:'expense',category:'Moradia'},
{id:3,description:'Mercado',amount:520,type:'expense',category:'Alimentação'},
{id:4,description:'Internet e celular',amount:160,type:'expense',category:'Contas'},
{id:5,description:'Lazer',amount:230,type:'expense',category:'Lazer'},
];
export default function App(){
 const [txs,setTxs]=useState<Tx[]>(initial); const [desc,setDesc]=useState(''); const [amount,setAmount]=useState(''); const [type,setType]=useState<'income'|'expense'>('expense'); const [category,setCategory]=useState('Outros'); const [goal,setGoal]=useState(5000); const [question,setQuestion]=useState(''); const [messages,setMessages]=useState<{who:'user'|'ai';text:string}[]>([{who:'ai',text:'Olá! Eu sou o FinanIA. Posso analisar seus gastos e transformar seus números em um plano de economia simples.'}]);
 const income=useMemo(()=>txs.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),[txs]); const expenses=useMemo(()=>txs.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0),[txs]); const balance=income-expenses; const rate=income?Math.max(0,balance/income*100):0; const months=balance>0?Math.ceil(goal/balance):0;
 const topExpense=useMemo(()=>txs.filter(t=>t.type==='expense').sort((a,b)=>b.amount-a.amount)[0],[txs]);
 function add(){const n=Number(amount.replace(',','.'));if(!desc.trim()||!n||n<=0)return;setTxs(v=>[{id:Date.now(),description:desc.trim(),amount:n,type,category},...v]);setDesc('');setAmount('')}
 function answer(q:string){const l=q.toLowerCase(); if(l.includes('gasto')||l.includes('onde')) return topExpense?`Seu maior gasto registrado é ${topExpense.description}, no valor de ${money(topExpense.amount)}. Suas despesas totais são ${money(expenses)}.`:'Você ainda não registrou despesas.'; if(l.includes('meta')||l.includes('econom')) return balance>0?`Hoje sobra ${money(balance)} por mês. Mantendo esse ritmo, uma meta de ${money(goal)} levaria aproximadamente ${months} ${months===1?'mês':'meses'}. Sua taxa de economia atual é ${rate.toFixed(1)}%.`:`No cenário atual não há sobra mensal. Primeiro precisamos reduzir despesas ou aumentar a renda antes de estimar a meta.`; return `Com renda de ${money(income)} e despesas de ${money(expenses)}, seu saldo mensal é ${money(balance)}. Uma boa prioridade é revisar os maiores gastos e definir um valor mensal realista para sua meta.`}
 function send(){if(!question.trim())return;const q=question.trim();setMessages(m=>[...m,{who:'user',text:q},{who:'ai',text:answer(q)}]);setQuestion('')}
 return <div className="app"><header><div className="brand"><div className="logo"><WalletCards/></div><div><b>FinanIA</b><span>Finanças pessoais com inteligência</span></div></div><div className="badge"><Sparkles size={15}/> MVP • Bootcamp</div></header>
 <main><section className="hero"><div><p className="eyebrow"><Sparkles size={15}/> Seu copiloto financeiro</p><h1>Entenda seu dinheiro.<br/><span>Construa seus próximos passos.</span></h1><p>Registre receitas e despesas, acompanhe sua meta e converse com um assistente que transforma números em orientações simples.</p></div><div className="hero-card"><Lightbulb/><div><small>INSIGHT DO MÊS</small><strong>{balance>0?`Você pode reservar ${money(balance)} este mês.`:'Suas despesas consomem toda a renda atual.'}</strong><span>{balance>0?`Isso representa ${rate.toFixed(1)}% da sua renda.`:'Revise despesas para recuperar margem financeira.'}</span></div></div></section>
 <section className="metrics"><Metric icon={<TrendingUp/>} label="Receitas" value={money(income)}/><Metric icon={<TrendingDown/>} label="Despesas" value={money(expenses)}/><Metric icon={<PiggyBank/>} label="Saldo do mês" value={money(balance)}/><Metric icon={<Target/>} label="Taxa de economia" value={`${rate.toFixed(1)}%`}/></section>
 <section className="grid"><div className="panel wide"><div className="panel-title"><div><h2>Movimentações</h2><p>Organize sua vida financeira sem planilhas complicadas.</p></div><BarChart3/></div><div className="form"><input placeholder="Descrição" value={desc} onChange={e=>setDesc(e.target.value)}/><input placeholder="Valor (R$)" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value as any)}><option value="expense">Despesa</option><option value="income">Receita</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option>Alimentação</option><option>Moradia</option><option>Transporte</option><option>Lazer</option><option>Contas</option><option>Renda</option><option>Outros</option></select><button onClick={add}><Plus size={17}/>Adicionar</button></div><div className="tx-list">{txs.map(t=><div className="tx" key={t.id}><div className={`tx-icon ${t.type}`}>{t.type==='income'?<TrendingUp/>:<TrendingDown/>}</div><div className="tx-name"><b>{t.description}</b><span>{t.category}</span></div><strong className={t.type}>{t.type==='income'?'+':'-'} {money(t.amount)}</strong><button className="trash" onClick={()=>setTxs(v=>v.filter(x=>x.id!==t.id))}><Trash2 size={16}/></button></div>)}</div></div>
 <div className="side"><div className="panel goal"><div className="panel-title"><div><h2>Minha meta</h2><p>Quanto você quer guardar?</p></div><Target/></div><label>Objetivo financeiro</label><input type="number" value={goal} onChange={e=>setGoal(Number(e.target.value)||0)}/><div className="progress"><span style={{width:`${Math.min(100,goal?Math.max(0,balance)/goal*100:0)}%`}}/></div><div className="goal-row"><span>Capacidade mensal atual</span><b>{money(Math.max(0,balance))}</b></div><div className="goal-row"><span>Estimativa</span><b>{months?`${months} meses`:'Requer ajustes'}</b></div></div>
 <div className="panel chat"><div className="panel-title"><div><h2><Sparkles size={18}/> FinanIA Copilot</h2><p>Converse sobre seus números.</p></div></div><div className="messages">{messages.map((m,i)=><div key={i} className={`msg ${m.who}`}>{m.text}</div>)}</div><div className="chat-input"><input placeholder="Ex.: Onde estou gastando mais?" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/><button onClick={send}><Send size={17}/></button></div><div className="suggestions"><button onClick={()=>setQuestion('Onde estou gastando mais?')}>Onde gasto mais?</button><button onClick={()=>setQuestion('Como está minha meta de economia?')}>Minha meta</button></div></div></div></section>
 <footer>FinanIA • MVP educacional criado para demonstração de Vibe Coding e IA aplicada a finanças pessoais.</footer></main></div>}
function Metric({icon,label,value}:{icon:any;label:string;value:string}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
